include $(TOPDIR)/rules.mk

PKG_VERSION:=1.24.2

LUCI_TITLE:=LuCI Support for cherry
LUCI_DEPENDS:=+luci-base +cherry

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature